import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/navbar/page";
import Footer from "@/app/footer/page"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ `${inter.className} bg-myWhite`}>
      <Navbar/>
        <div>
      <main className="mx-auto px-6 py-12">{children}</main>
        
       
        </div>
        <Footer/>
        </body>
    </html>
  );
}
